actions:
  post:
    loginstall: "echo {{@@ _dotfile_abs_src @@}} installed to {{@@ _dotfile_abs_dst @@}} >> {0}"
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  default_actions:
    - loginstall "/tmp/dotdrop-installation.log"
dotfiles:
  bash:
    dst: ~/
    src: bash
    link: link_children
  git:
      dst: ~/
      src: git
      link: link_children
  misc:
      dst: ~/
      src: misc
      link: link_children
  tmux:
      dst: ~/.tmux.conf
      src: tmux/.tmux.conf
      link: link
  tmux-confdir:
      dst: ~/.tmux
      src: tmux/.tmux
      link: link_children
  vim:
      dst: ~/
      src: vim
      link: link_children
  zsh:
    dst: ~/
    src: zsh
    link: link_children
profiles:
  home:
    dotfiles:
      - bash
      - git
      - misc
      - tmux
      - tmux-confdir
      - vim
      - zsh
